# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-24 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=models.TextField(),
        ),
    ]
